name: Deploy
run-name: Deploy landing page to lyj.kr
on:
    push:
        tags: [v*]
jobs:
    CI-CD:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Docker build & push to prod
              run: |
                  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                  docker build -f Dockerfile-dev -t ${{ secrets.DOCKER_USERNAME }}/lyj_landingpage .
                  docker push ${{ secrets.DOCKER_USERNAME }}/docker-test-prod

            - name: Deploy to prod
              uses: appleboy/ssh-action@master
              id: deploy-prod
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ubuntu
                  key: ${{ secrets.SERVER_PRIVATEKEY }}
                  envs: GITHUB_SHA
                  script: |
                      sudo docker ps
                      sudo docker pull ${{ secrets.DOCKER_USERNAME }}/lyj_landingpage
                      sudo docker run -d -p 9003:3000 ${{ secrets.DOCKER_USERNAME }}/docker-test-prod
                      sudo docker network connect lyj_default
                      sudo docker image prune -f